#ifndef SEMANTIC_VERIFY_H
#define SEMANTIC_VERIFY_H

enum semantic_verify_kind {
	SEMANTIC_VERIFY_UNCHECKED = 0,
	SEMANTIC_VERIFY_SKIPPED,
	SEMANTIC_VERIFY_RAW_CLEAN,
	SEMANTIC_VERIFY_RAW_MODIFIED,
	SEMANTIC_VERIFY_SENSITIVE,
	SEMANTIC_VERIFY_STRUCTURAL,
	SEMANTIC_VERIFY_UNSTABLE,
	SEMANTIC_VERIFY_ERROR,
};

#endif /* SEMANTIC_VERIFY_H */
